"""empty message

Revision ID: 0525c0670c5a
Revises: 900d6e9fa068
Create Date: 2020-04-14 22:46:25.123205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0525c0670c5a'
down_revision = '900d6e9fa068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('user', 'pasword_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pasword_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
