"""Add initial BasicStrategyPlayStats table

Revision ID: 172aa151d202
Revises: cc1c2f7fa479
Create Date: 2020-04-23 19:22:17.319053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172aa151d202'
down_revision = 'cc1c2f7fa479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_strategy_play_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basic_strategy_play_stats')
    # ### end Alembic commands ###
