"""playstats and streak both in playstats table

Revision ID: ec9146a96270
Revises: 83d9ff5fe5ab
Create Date: 2020-04-25 18:19:14.195293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec9146a96270'
down_revision = '83d9ff5fe5ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_strategy_play_stats', sa.Column('play_stats', sa.LargeBinary(length=1024), nullable=False))
    op.add_column('basic_strategy_play_stats', sa.Column('streak', sa.Integer(), nullable=False))
    op.drop_column('basic_strategy_play_stats', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('basic_strategy_play_stats', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('basic_strategy_play_stats', 'streak')
    op.drop_column('basic_strategy_play_stats', 'play_stats')
    # ### end Alembic commands ###
